const create2DArray = (input: string) => {
  const lines = input.split("\n");
  const grid: string[][] = [];
  for (let i = 0; i < lines.length; i++) {
    grid.push(lines[i].split(""));
  }
  return grid;
};

const isWithinBounds = (x: number, y: number, grid: string[][]) => {
  return x >= 0 && x < grid.length && y >= 0 && y < grid[0].length;
};

const findOccurrences = (grid: string[][]) => {
  let counter = 0;
  for (let i = 0; i < grid.length; i++) {
    for (let j = 0; j < grid[i].length; j++) {
      // horizontal
      if (
        grid[i][j] === "X" &&
        isWithinBounds(i, j - 1, grid) &&
        grid[i][j - 1] === "M" &&
        isWithinBounds(i, j - 2, grid) &&
        grid[i][j - 2] === "A" &&
        isWithinBounds(i, j - 3, grid) &&
        grid[i][j - 3] === "S"
      ) {
        counter++;
      }
      if (
        grid[i][j] === "X" &&
        isWithinBounds(i, j + 1, grid) &&
        grid[i][j + 1] === "M" &&
        isWithinBounds(i, j + 2, grid) &&
        grid[i][j + 2] === "A" &&
        isWithinBounds(i, j + 3, grid) &&
        grid[i][j + 3] === "S"
      ) {
        counter++;
      }
      // vertical
      if (
        grid[i][j] === "X" &&
        isWithinBounds(i - 1, j, grid) &&
        grid[i - 1][j] === "M" &&
        isWithinBounds(i - 2, j, grid) &&
        grid[i - 2][j] === "A" &&
        isWithinBounds(i - 3, j, grid) &&
        grid[i - 3][j] === "S"
      ) {
        counter++;
      }
      if (
        grid[i][j] === "X" &&
        isWithinBounds(i + 1, j, grid) &&
        grid[i + 1][j] === "M" &&
        isWithinBounds(i + 2, j, grid) &&
        grid[i + 2][j] === "A" &&
        isWithinBounds(i + 3, j, grid) &&
        grid[i + 3][j] === "S"
      ) {
        counter++;
      }
      // diagonal
      if (
        grid[i][j] === "X" &&
        isWithinBounds(i - 1, j - 1, grid) &&
        grid[i - 1][j - 1] === "M" &&
        isWithinBounds(i - 2, j - 2, grid) &&
        grid[i - 2][j - 2] === "A" &&
        isWithinBounds(i - 3, j - 3, grid) &&
        grid[i - 3][j - 3] === "S"
      ) {
        counter++;
      }
      if (
        grid[i][j] === "X" &&
        isWithinBounds(i + 1, j + 1, grid) &&
        grid[i + 1][j + 1] === "M" &&
        isWithinBounds(i + 2, j + 2, grid) &&
        grid[i + 2][j + 2] === "A" &&
        isWithinBounds(i + 3, j + 3, grid) &&
        grid[i + 3][j + 3] === "S"
      ) {
        counter++;
      }
      // secondary diagonals
      if (
        grid[i][j] === "X" &&
        isWithinBounds(i - 1, j + 1, grid) &&
        grid[i - 1][j + 1] === "M" &&
        isWithinBounds(i - 2, j + 2, grid) &&
        grid[i - 2][j + 2] === "A" &&
        isWithinBounds(i - 3, j + 3, grid) &&
        grid[i - 3][j + 3] === "S"
      ) {
        counter++;
      }
      if (
        grid[i][j] === "X" &&
        isWithinBounds(i + 1, j - 1, grid) &&
        grid[i + 1][j - 1] === "M" &&
        isWithinBounds(i + 2, j - 2, grid) &&
        grid[i + 2][j - 2] === "A" &&
        isWithinBounds(i + 3, j - 3, grid) &&
        grid[i + 3][j - 3] === "S"
      ) {
        counter++;
      }
    }
  }
  return counter;
};

const findXOccurrences = (grid: string[][]) => {
  let counter = 0;
  for (let i = 0; i < grid.length; i++) {
    for (let j = 0; j < grid[i].length; j++) {
      if (
        ((grid[i][j] === "A" &&
          isWithinBounds(i - 1, j - 1, grid) &&
          grid[i - 1][j - 1] === "M" &&
          isWithinBounds(i + 1, j + 1, grid) &&
          grid[i + 1][j + 1] === "S") ||
          (grid[i][j] === "A" &&
            isWithinBounds(i - 1, j - 1, grid) &&
            grid[i - 1][j - 1] === "S" &&
            isWithinBounds(i + 1, j + 1, grid) &&
            grid[i + 1][j + 1] === "M")) &&
        ((grid[i][j] === "A" &&
          isWithinBounds(i - 1, j + 1, grid) &&
          grid[i - 1][j + 1] === "M" &&
          isWithinBounds(i + 1, j - 1, grid) &&
          grid[i + 1][j - 1] === "S") ||
          (grid[i][j] === "A" &&
            isWithinBounds(i - 1, j + 1, grid) &&
            grid[i - 1][j + 1] === "S" &&
            isWithinBounds(i + 1, j - 1, grid) &&
            grid[i + 1][j - 1] === "M"))
      ) {
        counter++;
      }
    }
  }
  return counter;
};

export const day04a = () => {
  const grid = create2DArray(input);
  return findOccurrences(grid);
};

export const day04b = () => {
  const grid = create2DArray(input);
  return findXOccurrences(grid);
};

const input = `XMSSMXMSMXASAMMXMXMSSSMMSMMMSXMAXXMSMSMXMAXSXSXSMMXSXMSSXMAMXMMXXSXSAMXASXMXXAXSXSXXMMSAMSSSMSMSAMXXXSXSMSSXSXMSAXMMMSMXSAMXMXSAMXAMAMXMXXXX
XSAAXAMMAXSAMSMSMSXAXAAXSAAAAMSSMMMAMAMXXMAMAMMSASXMASAXXSMXSSSMMSASAXXMSAMASXMMMSMXSAXAXMAMAAMMMSSMMSAAAMAASAMXSAAAXAMXMMMXSAMASXSSMSMMMXMM
MMSSMSAMXMAAXXAAAXMASXMMSSMXSMAXMASASXSMMXSMAMAMAMXXMMMAXAMXXAAXAMMMMMMXSAMAXAAXAXAAMMSMMMAMMMSMAAAAAMMMMMMMMAMAMSSMSMSASAMXMMSMMAASAAAAAAAA
XAAMAMSXMASMMMSMSMAMXAMMMASXAMAMMMSXSMMAXAMXSMSMSMMMAAXSAMXSMSMMSXMAAAXASAMAMSSMMSMMSXMMAMAMAAAMMSSMMSAXAAXMXMMMMAMAMXAASXSSXXAAMMMMSMXXSSSS
MMXSAMMMMXMXAXXAAAXASXMAMAMSXMSASASASASXMXSAMXMAXAXSXMSXXMAXXXMAMASXSSMMMXMXMMAXXAAXXMASXMAMSMMSXMAXASMSMSSSXXAXMXSMAXXXMAMAXSSSMSXMXSSMXMAX
AXMSMSAASAMSXMMSMSXMSAAMMSXMMMASMAMASMMXAAMXSAMXMSMSASXMAMSXSASXMMMMAMMMMSXMASXMMSSXSMMMAMSXXAAXMXAMXSASAMAMMSMSMAXMAXSAMAMMXMAAAXXXAXXAXXAM
ASMMXSMXXAMMAMAMAXMASMMMAMAAASMMMSMMMMSMSMSASXMXAAAMMMASXMAAMAAXXAXMASAAASAMAAASXXMXXAAMXMMASMMMSMAXMMAMMMASAAXAMMSMSSXASAMXAMSMMMSMMMMSMMSS
MXAMMMMSMSASMXSSXXMXSXSMXSSSMXXSAXXXAAAAASXMSAAXSMSMASAMAMMSMAMMMMMSAMXSXSAMXSAMMAMMSXMMAXMAMAMAXMXMAMAMXSASMSSSXMAAXMXMMMSSSXMAXAAMAAAAAXAM
MSSMAXAAXXMXAMMXMXXXMASAXAAXAMSMMSMSSSMSMSXXSMSXMAXMXMAXSMAMXSAAAAAMASAMXSAMAMAASXSAMASXMXMASXMMSMMAMSASMMASAMAMASMSMSMSAMMMXMMMMMSSSSSMSMAS
XAXSMMMSSSMMSMSASMXAMMMXMMSMSMSAXMAAMAMXXMMMMAMXMAMSMSSMMXXSAXXSSMMSMAAMASAMXSSXMXMMSAMASMSAMAAAAAASXSASXMAMXMAMMMAAXAXMAMXSAMSSSMXMAMMXXMMS
MMXAXSMMMAAXAXSAAASAMXAXMXMAMASXSMMMXXMXAXAMMAMAASMSAAXXSAMMXSMMAMMMAMSMXSAMXMAXMAMAMASAMXMXSSMSMXSAXMAMMMXSSSMSAMSMSMSSSMMMXSAAAAXXSXSMSMSS
SSMSMMAASXMMMXMSMXXAXMMXMAMXMXMASAXMASXMSSMXSASXSMAMMMSAMASAMXXSAMXXMXMMXXXXAXAAMAMAMXMXSXMMAMAMXMAMXMXMASAXXAASAMXXMXXAMXMSMMMXMMMAMAAAXXAS
MAAMASXMMXAAXAAMXMMMXXAAXAMAMAMSXMAMAXAAMXXXSXSXXMSMMAXMMMMMSMMMAMMXXAASXMASMMSXMAXXSMMMMAXMASMSMXAMXMXSAMXSMMMMAXXMSMMAMMAAAAAASXMAMSMMMMMS
SMMMAMXAAXSMMMMMAMAMMMSMMAMASXSAAMASXMMMMAMMMMSXMAXXSXXMAAAXAAMSSMAMSSXMAXAAAAAXSSSMAASASMSAMXAAMSMMXAAXASASXMASXMXAAASAMMSXSMSXSAMXMAMAAXAS
SAMMSMMMSAMXMAMSMSAAAAAMSMXMSXSMASASAMAMMAMXAAXXXXMAMXASMMXSSXMAAMXMAAASMMSSMMSMXAAMSMMAAAAMXMMMMAASMMMXAMXXAMXSSSMMSXMXXXMXMAXMSAMXMAXSXSXS
SAMSAMXAXMASMAMAAXMSMSSMASAAXAMXMAXMXMAXMASXMSSMMXMAXXXMMSMMMSMMSMMMSXMMAAXXMAXXMSMMMXMSMSMMSXSXMMXMAAXAXMSMSMSXAXAMXAMXSAASXMSXSAMXSMMXAMXS
SMMSMSMMSMAMXMMMSMAMAAMMASMSMMMMMMAMASXXSASXMMAXAXMMSMAMAAAAAXXAMMSAMASXXSXAXSXMAXMAXAXXMMMMAASMXSASXMMSAAMAMXSMMMSMXAXAXMMXAXXMMAMAAAAMASAM
XAAXMXAXXMASAMAAAMAMXMSMXMXAMXAAAXMSXXAXMXMASXMMMXMAAXAMSSSMSSMXSAMASAMSMMMSMAAXSXMMMSMAXAMMMXMAAAAXXAAXMAMSMMSAMAASMMMMMXAMMMSXSAMXMMMSAMAS
XMMSSSSMMXAMASMSSSMSMAXMAMXMSXMXSSXMAMSMSAMXMAMSMSMSSSXMMAMXXXASMAMMMXMAXMAMASXMMMXMAXSMMXXAXAXSMMAMMMSSMAMAAASAMMSXMXAXAMXSMASAXSXSMMXMASXM
XAAXXAAASMSXMMMAMAAAMMMMMMSXMASXMMAMMMMASAMSSSMAAAAMMMMMXAXMAMMMSXMAAMSMSXAXMXMAXAXMAXAXMMMSXXXAXXAXAMXXMASMMMSXMXMXMMXMXSAAMAMAMMMSAMSSMMAM
MMMSMMMMMMMASXMMSMMMMAXXAXAAMAMMASXMAAMAMAMAAMXMMMMMAAMSSSMMAAMXXXMMSMAMSXMSMMSSSSSMSSSMMAXMASXSMXSSSMSSSMXMAMSXXAMAMSMAAXXXMASAMXASAMAAXSXS
SASAAAMASASAMAAAAAMXMAXXASMXMAMSAMASXXXAMASMSMSSMSAXXMSMMMASMSSMMXSAAMAMMAXAAMAXMASAXXMAMSAMXMAMAAXAMAAAAMMSAMMMMSSXSAMSAMXXMASAXMMMAMSSMSAA
MXSMSXSAMMMASXMSSMMSMAXXAMXMSSMMMSXMASMXSAMXMAAAASMSSMSAAXXMXMAXAAMSMSMSSMMSXMXSMMMXMASAMMMMSMMMMMMAMMMXMMAXXSMAXAAMSXMXAMXMMMXXXMSSXMXMXMAM
MMXXAMMAMXSXMAAXAASMMAXAAXMASMXAMAXMXMAMMMMAMMMMMMASAASMMSXMASXMMMMAXAMAASAXMSMMMXMMSAMASMXAXMXXSMMSMMSSSMMSAMXSMMSMMASMMMAMSSSMMXAAXSMMMAMX
XSAMXXXAMAXAXMMMSMMAMAXSAMMSMXSMMAXMMMXMAASAMXSAXASXMMMAXAASXSMASXXXSSSSMMSMXAAAXASXMASAMMMSSMSAMXMMAAAXAAAMAMAMXXAXSXMAXSASXAAAAMMSMSAAMMSM
AMAMSASXSMASXAXXXMSSMMMXAXXXXMAAMSXSAAXMSMXXSAXXXSAMXASXMSXMXSASMMMXXAAAXSMXSXSMSXSASAMAMAAMSAMXMASXMMSSMMMSMMXSMXMASASMMSSSMSMMXSAMASMMSAAA
MSAMMMSAAMAXMMMSMXAXAMSSMMSXMASXMXASMSMAAAMSMXMXMAMSXMXAMXASAXXAAAMASMSMMXMAXAAAMMXXMASXSMXSMMMSSMSXASAMMAAAXMXMASXMSAMMASASAMAAAMAMXMASMMSS
XSXSAAMMMMMSAXAAXMASAMXXMAMAMXMXSMMMAMASMSMAASMSXMASASXMSSXMASXXSASXSAAXAAMAMSMMMMXSMMXMAMXMASAXMASMMMASXMSXSXMMMSXMMAMMSMAMXSAMXMAMASXMAMMM
MXXXMSSSXMASMMSSMSAMXXXMASMXMAMXXAXMAMMMXXMMXMAAAMASAMAAXMAMAMXXMMAMMMMSSMMXXXAMXSAMASXSAMXSAMMSMAMAXSMMXAMASMMAASAMMSXSAMXMXSMMSSMSXSXMXSAM
SXSXSAAMAMMSXMAAXMASMMSAAXMAMAXASXMMSSMXSASXSMSMMMASASMMMSMMASAAMSAXSXMXXSMMMSAMAMASMMASXMXMXSMAXSSSMSMMMSMAMASXSXMMAMMSASXMAMAAXAAMAMAMAMAX
MAMMMSSSXMXMMMMXXXAMXXAMXXMMSSSMSAAXAAXAMXSAAAXAXMXXAXAAAAXASMMMAMMSMXMSMAMAMXMMASXMXMAMASXMXMMMXMAAAXAAAAMXSXMMAMSMMSASAMAMXSMMMAMMAMAMMMSM
MAMAAMMMAXSXAXMASMMSSXSSSMMMMMAASASXSMMSMAMXMMSSMSASMSSMSSSMAXAMASXMXAXAAXMXSAXXAMXMAMASXMAXXMASXMSMMMSMSSSXMASMMMXAAMMSMSSMMMMMSMMMAMXSXAXS
SSSMXSASAMASXXSAMAMXAAAAXMXAASMMMAXAAXSAMAXXXAAXASAMXAXAAAAMMMXMAMAASMSMSASAMAXSASASAXMSMSXMXSAXXAXMSAAAXAMMMAXMSMSMMSAMXXMASAAXAMSMXSMXMAXA
XXXAASASAXMASXMASXMSSSMMMSSSXMASMMMSMMSASXSMMMSSMMAMMXMASMXMAAAMXXMMAAAAMMAAMAMSASMXSASMXSSXAXXSMXMXMXSXMMXAMMSMAMSAASXSMMSAMXSMSMSAASXMASAM
SAMMMSMMMMXXAXMAMXAAAXXXAMAMASAMAXAAXXSXMXAXXAXMMAXXMXSMXMASMSMMSAXSMMMSMSSXMXMMAMXAXMAXAMMMMMSAMXSASAXASXMASMAMSSSMMSAXAAMASAXXMAMXMMAMAMAX
SXMMAXMXSSSMASMSSMMMSMSMMXAMAMXMSMSXSMMSSSXSMMMSXMMSXAXMASAMXXAASAAMSMSXMMMMSXMMAMMMSXSMSMMAMSXMASXAMAXMMMXSSMSSMAXMSXXSMMSAMXSAMAMAXXXMASMM
SAXSMSMSMAAMMMAXXXAXXMMAASMMSXMAXAXAMXAAMAAXXAASMSASMSMSAMXMSMMMSAMXAXMAMMSASAASASAXMAMAAASXSMMMMMMMMMMAAASAMXMAMXMXXAXXMAMASXXXSASMSMSSXSXA
MAMAXAMAMSMSAMXMMXSXMASMMSXAMAMAMAMSMMMSSMSMSMMSAMXSAAMMMSAMXAMAXMASMMMAMXMAXXMAMSMSXXMMMXMMAMASASAAASXMMSMASMSXMAMMMMMMMXSXMAXMXXSAAAAAAMMM
SAMMSXSAXAXSXSXAXMMAAXAMXXMMSAMSMMMAXSMMXXAAXXXMXMAMMMSAASXSXSASMXMMASXMMXMAMMAMXSMMMMMXSXSAMSMMASAMXXSAMXXASXMASXMAMXAXAXXMXSAXXAMMMXMMMMAX
SMSXAASMSMXSMMMSXAMSMMASAMAXMXMXAXSASAMXMSSSMMXSXSXXAXSXXSAMXMAMMMSMAMASMSMAXSAMAMAAAASMSASMXSXMXMMSSMSMMXMMMASXMMSSSMSSMSAMXAAASXSAMXSSMSSS
XAAMMXMAAXASASAMMSMAASAMMMAMMAMXXMASMXXSXAXAAXXXAMXMXMXSMMXMMMAMAAAMASMAAAMAMSAMSAXSXXXAMAMSAMAXSAAXMASXXSMMMAMXMAMMAXMAMMAMMMMMAAAASMMAAAAX
MMMMSMMSMSASXMASAXMXMMASAMAMMAXSAXXXXMXAMXSMSMMMMMAMXAAXXAXMSAASMSSSMSXMMMMSXSXMXAMXXSMSMXMAMSAMMMMSMAMMSMAAMSMSMSSSSMSMMSAMAASXMMSXMASMMMSM
MSAAAAAAAAMXASAMXSMSSXXMAMAXMASMXMMMAXSMMASAAMXAAXAXAMSMMMSXAXMAXAAMMMAXXSMMASMMMSMSAXAAXSMXXMASXAAXMASXAMMMXXAAXXMAAXSAASXMSMSXXMAXMMMMMXXA
ASMSXXMMSMXSXMASXMAAAXSSSMASXXSXXMMMMMAXMAMXMASMSMSAMXMAAAXMMMSXMMSMMSSMASAMAMAXSAAMMMSMMMSMASXMXMMMXAMMXXSMMMSMSSMSMMSMMMXAAMMMMXMXMAXMMAXS
AXXAXSAMMXAAAMSSMMMMSMAAXMAMXASAXSAASAMXMXMMXAXXXAAXAMXMMXSAAAXAXAXAAAAAASXMASMMMMMMXMXSXAASMMXAAXASXSSXSASAAXXMAXMAMAMXAMSSSXSAMAMMSSSXMXSX
MAMAMSAMASMSMMMXAMMXMAMSMSMXMXMAMSSSSSXSMSSSMMSXMXMXMASXSXSXXSSSMMSSMSSMMSMSXMMAXAAMMMAMMXMSXAMSMSMSAAAAMAMXMXAMXXXMMAXMXMAAXMMMSASAAMXXXMXM
SXMSXSXMASXXMAXXAMXAXMAXAXXXSXMXMXMMMMMAAAAXXMAXAAMXXSAXMAMXMXXMAXXXAAXXSXAXAMSXSMXSAMASAAMXMMXAAAXMMMMMMMMASMSMMSSSSSSMMMMSMSSXSMSMSSMXMMAA
MXMMASXMASMMSASXXASMSSMMSMMASXMXMASAAASMMMSMMXSMSXSAMXXAMAMAMXSMSMXMMMMSAMXMSMSASAXSASXSMMMAMXSMSMMXMXXMASXMXAASAAAMXMAMASMMAXMASAMAMAXXAMSM
AMXSAMMMMSMAMAXXMXMAAAAAMAMSXAMXSASXSMSXSXAXSAXAXAMMSSSMSASASXAMAAXSSXMXXXSXMAMAMAMSAMXSAMXSAMSXAXSMXMXSASAAMSMMMMSMMSXMXMAMSMMAMAMSMAMSSMXX
SAAMAMAMXMASMSMASMSMSSMMSXMMSAMMMXSAMXMAXMAAMAMXMSMAAXAAAASASXMSSSMAMAMXMXMAMSMMMMMMAMXMAMXMASMMMMAXAAAMASMMMMAXXAMMAAASMSMMXAMMSXMAMAMSMXSA
AMSSSMXSAMXMAMAXAAAAAAAXMMAXMXSXXASMMXMAMMMSMSMXXMMMSXMMMXMXXAXAMXAASAMMMAMXMAAXXXXXSXMSAMXSMMMAAAMSXSXMXMXSASMMMSSMMXMMAAXSXSAXSMMMSMXXAAMM
MAMAAASMMMXXXXXMMSMMSSMSMSSXMSAMXMMAMMMSSXAMAMMSMXMAMXXAXXAASMMMSASASAMASASASMSMMMMMMAMMMXMAXASMXSXSAMXSXMXXAXAAAXXXSMAMSMMXAXXXMAXXXMSMMMSX
XSMMMXSAASMSMMSMXXXMAMXSAAAASXMXSXSXMMAAXMXMAMXAAXMAXAMXXSMMAAXXMAMASXMXSAXXSAAMAAMAMXMAMSASXXSAAMAMAMAAAMSMMSMMXXMASXMMMXAMXMMMSXMASMAAAXMX
XXAXSAMMMAAXAAAXMXAMXXAMMMSMMAXAMAMMSMMXMSXMASMMSSMSSSSSMXSMXMMMMXXMMMMMMMSAMXMMSSMAMSASMSAMMAMMMMAMAMSSMMAAXSXSSSMASAMMSMMMMAXAMAMAASMSMSSX
ASMMMXSXMMXMMSXSMSSMSMSSSMXASXMSMAMAMMXSAAXSASAXAXAAXAAAXAXXMXMSASMXMAMAAMMMSSXMXXMASMAXXMAMMAMASMXMXAAXASXXMMAMAXMAXAMASXAASAMASXMXMMXMMSAS
MXMAMXSAMSMSMXAAAAXAAAAAAASAMAAMMMXSAAAMXMXMASMMASMSMMSMMASMAAXXASAAMSMMMSAAAAASASMXMMAMMMMMXAXMMMMMMMMMXMMXSXMMMMSASXMAMMMMSAAMMXMMXMAMXSAM
XAMASAMXMAASAMSMMMMSMSMSMMMXMMXMASMMMMMSAXXMXMXMMSXAAXAAMAXAXASMMMMMXXAAASXMMSMMASMSXMASAAASMMSSMSAXSASASXSAMAMXXAMAAXMSSXSAXMXAXAXAAMMSAMAM
SXSSMMSAMMSMAAMMASXMAXXMAXMXSXXSASASMMAMMSAMXAXMAMXMSSSSMMXSAAMAAAXXASMMMSASXMXMXMASMMASMSMAASAMASAXSAXAXAMMSSMSASMMMMAMAAMAMSSMSMMSMXXMASMM
MMMXAAAAMSXXMMMSASAMXMASXMXAXMAMXMXMAXSSXMASXSMMMSSXAAAAAMAXMMSMMSSMAXXAMXAMAXSSMMAMXSAXAXXSXMASAXXXMAMSMMMXMASAXMXSSXAMMMMXMAAXAMAMMMXXASAS
MAAMSMMSMMAXMAMMMXXMAXMSAMMMMMMMAMSASAMXASAMXMMXXAAMMSMSMMMXXMAMSXXMASXMMMXMSMASAMXSAMASXMAXXSMMMSMXMAMXAASASMMMMMXMMSMSSMMSMSSMMMAXAASMXSAM
SMSMXAAXMMXMMASMSMAXMXXXAMSAMMAMAXMAMMSSXMAMSXSSMXSAMMAAXAXMXMAMMASAMAMSASAAMMXMSXXMASAMAMXMAAXAXAAAMAMMSMSASXAAMAMAAMXAAAAXMMMMXMSSSMXSAMAM
XAXXSMMSAMSXSMXAASAASMSSSMMAMMAMSSMAMAMMASAMAAAXMAXAAAMMSSSMXASXSAMAMAASASMSMSMMMMMSXMASAMMMAMXMMSMSMMMMMXMXMMMXMAMMXMMSSMMMMXAXXMAAASAMXSXM
MXMXXAXSAMAAXAMSMMSSMAXAMXSAMSSMMAMXMASAAMAXMMMAMMSAMXXMXMAMSXXAMXXXSMMMXMAMMMAMXAAAMSXSXSAMSXSSXMAAMSAMSSMMSSSMSXSASXMMXAAAMMMMMMMSMMXSXMMS
XAMXSXMSAMMMMXMAAXXXMMMSMAMAMAAASXMASXSMMSSMXSSSSMSMSMMMASAMXMMMMAMXXMSMMMSMXXSXXMMSASMMMMASMAAXAMXMASASAAAAASAAAAMAMAASXSSXSAAAXMAMXMMMAMAM
MSSMMAASAMAAMXSMSMMMMSAMMSSXMMSMMAMXMMMXMAXMXMAMXAXAAAASMMASXAMASMXXASAAAMAAXSASXXMAMXAASXMMMMMMXMAAMSXMAXMMXMMMMXMASMMMMMAMSXSMMMASAXASAMAS
SAAAMMMXMXSMSAAXMAXAAMAMAMMMSAMXXMXAXAMAMXSAMMASMMMMMSMSASAMMSMAXXASMMSSMMMSMMAAMMSSMXSMSAMXXAXAMSMSMSMSSSMSSMSSMXSAXMAAMMMMXAMASXMSMSXSAMAA
MSXMXSMMSAAAMMSSSMMMMSXMMMAAMAMXMASXSMXMSAAAXXAMAXAMAMXSAMXXAMMXSMXMSAMXMXSAXMSMSXAAAXXXSAMXMMXSAAAXXXAAAAMAAAAAXXMASXSMXSXSMSMAMAAXASMMMSMM
MAXXASAAMMMMSAAMXAAMMMAMAXSSMSSSMAAAXXASMMSSMMSSMMSMMSAXXMMSSSSMAMAMMMMAMXAAXXXXAXAMXMSASAMXAAAXMMSMMMMMSMMSXMXMMSMXMXXXMXAMAXMMSMMMXMASAAAX
MSSMASAMXAASMMXSSSMSAMAMMXMAMAAXMMMXMMMSAXMAXAAAAAXASMMSASAAMAAAMMAXAAXAXAMXMXMMMXMXMAMXMAMSMSMSAMXAAXAXMXMMAMMSMMMMSAMAXMAMSMAXXXXMASXMXSXM
SAXMAMAMMSMSAAAMXAXSASMXSASAMMSMXAMASXMSMMSMMMSSMMSSMAASAMMSSXMMMSXXMXSMSMXAAMSAMASAMSSMSSMXXXASXMSXMSMSMSAMXMAAAAAXMASAMXAMAXMMSMMSASAAMXMX
AMMMXXXMXXSSMMXSAMXSAMMASASXSXXMSMSAXAAXAAXXXMAMAAXXMMMMMMMAMASXXXMASMMMAMSMMAXASASXSASMAXXXMMMMAMXMXAMMASXMAMXSSMMXSAMAXSASMMSAAMAMXXMMAMXM
MXMXMASXXMASXXXMXMAMMMMAMMMASAMAAAMASMMSMMSMXMASMMXSMSXSAXMASAMAXMMAAAXSAXAAXSSMMMSXMAMMAMMSAAASASAMSAMXAMASXSAMMAAAMAMAMXAMAAMSSSSSSXMMAXAA
XMMAAXMASMAMMSAMXMXSAXMASAAXSAMSMSMAXAXXXAAXAMXSASMAAAAXASXMMMSSMXMASXMAMMMSMMAMAAXAMAXMAAXSXSXXAMAXSAMMASXMAMAMMMMMSAMMMMSSMXMAMAXAAAXSXSXS
XSSSSSXMXMXSAMAXAXAXXXMAXMSMMMMAAMMXSSXMASMSSSMSAXSMMMSMAMXAXAAAAXMMXMAXXMXXXMASXSSXSAXXAXXSAXASXSSMSXMXXMMMMMASXMSASAMSAAXAXSMAXSMMMSMSAMXM
AXAAAAXXAXMMMSMMMMMSMSMSMSAAAMSMSMMAXMAMAAXSXAXMMMMMAAXMAMSMMMSSSSSMSMXXAMXMAMXSAAAASAMSSMMMAMAMAAXAMAMMSAMAMMMSAAMASAMMMMSMMSSSMXXXAXMMAMAM
MMMMMMMSMMAAMAXMAAMAAXAAXMSSMXAXXAMMSSMMSSMMSAMXSAXXMSSSXMMMAXXAXXAASAASXMAXMXAMMMMXMAMAMMXMXMAMMMMXXAMXSAMMSAAMMMMAMAMMSXMXMMAXAXMMMSAMXSMS
MAXXXMASXMXXSASMMSSMSMMMMXAXXSXMSAMAAAXAAAAXSXSAMXSAMXMASMMSXSMXMAXMMXMSASXSXMASAXXSSMMAXMAXSMXSXXXXXXXMSXMASMSMAXMASXMMSAMSXMAMMMSAMXAAAAMA
MXMXXMASAXSAMMMAMXAXXXMASMAMMXMAXXMMXXMMSSMMMMMXMASMMMXAMMAXMAMXXMXSXXXSASAAXAMXMAMAASMMSSSSSMMSXMXMASMMMAMXMMMMAXXAXAMAXAMAXMASAASXMMXMXMSM
SSSMXMASAMMAMXMXMSAMXAAAMMMMXXAMXSSSSXSAAMXMAAAAMXMAAAMXMXAXSAMXSMASXSAMAMXMXXMASXMAAMSAMXMAMAAMAMAAMAASMXMXSAMXMAMMMSMMSSMMMSAMMXSXMXMSMXMM
XAAXXMXMXMMAMXASASXXSMMXSASAXMSMAMAAMAMMXSASXSSMSMSSXSMMSMSMSASXAMASAXAMXMXXMASAMXMMSMXMSXMAMMMXAMMSMSAMXMSSMMSAMSASAAAXAAMXXMMXSAMASAAAAAXA
MSMMXSAMMMMSSMXSAMXXMASMAAMXMXAAAMMMMAMAASASAXMMAXMAMAXMAAMAMAMMAMXSMSMMMMMSSMMMMSXAXAAMSMSXSASMMXAXAAMAMXMAXAXAMXAMMSMMSSMSMMMAMXSAMMSMMXSM
MAXAXXAMXSAAAXAMAMXXMAMAMMMXMSASMSMMSASAXMAMXMAMMMMASAASMSMSMSAMXAXSXAXAAAAMAAASASMSSMMMSAAAMAXAXMXSSMSAMASMMMSSMMXMAMAMXAASASMSXXMASAMXSMMM
SMMSSSMMAMMSMMXMMMXMMASXXAMAMAXMAXMASXXXXMXMSMMMSASXMMMXAAAAXXXMXXXMASMSSMSSMMMMASAMXMMAMMMSMXXMMSAAAXSASASXXXAMXXSMMSAMSMMSSMAMMMSAMAMAAAAA
XAAAAAAMAMMXXXSAMXAMSASASAMASMSMSMMMMMXMAMAMXMAAXMSXSAXMSMMMMXXSASMSMMAMAMXXXAXMAMAMSMMAXXMMMAAMAMMSMMSMMASAXMXSMMMAASAMXXAMXMAMAASASAMSSSMM
MMMMXXMSMSMMMASAMMMMMASAXXSMMXXAAAAAAMAAASASASMSSXSAMXSXXASXSMAMMSAAXAAXASXMSASMASAMXXSSSSXAMSSMASAAXMMMMMMMMMASAASMMMXXMASAMXXSMMMMMXMAAXMM
XSSMXSAMAAMASASAXSAAMMMXMMXMSSMSMSMSMMXXMMASXSAMAMMSMMMMXMMAXMAMXMXMMSMMMSAMSSMMMSASAMXAAXMXMAMMXMMSSXMAAXAXAMASXMMMAMSMSAMASMMMASXXAMXMSMSA
MAAAAMXMSMMXMASXMSMMXAMXXMAMAAAXAXAXMSMSXSAMAMXMMSAXMSAAXSMMMSMSAASXMASMMSAMSAMXMSAMMMMMMMMSSSSSXSAMAASXSSMSMSASAMXMAMMAMXSAMAASMMXSAMXXMAMX
AMMMMMAAMMMSMMMAXXASAMXSASAMMMXMMMSMMAAAAMAMSMSSXMASASXXMAAMAAAXMXSASASMAMXMSAMXXMMMMXMAAAMMAMAMAXSMSMMAMXAAMMMSXMAMMXMAMXMXMMMXAAXSMMAMMSMM
SXMSSSSSMMAAAASXMMAMAMAMMMASXAXMAMAASMMMSMSMMAXAXMAMXMASXSMMSMSXMAMAMASMXXAMXAXXMASMMAMXSSXMSMMMMMMXMXMMMMXMSMMMXMXMMAMAXMSAXSSXMMMSMMXXAAAX
AAMAAXAAMMSSSMXMAAMSXMASXSXMAAMXASMMMASAMXAAMAMMMMASMMMXAAXMXAXXMSSSMMMASMSMMXMMMXMXSAMXAMMMMAAMAASASXMXXMSMSAAMMXMASMSXSAMXMXAASAMXASXMXSMM
SMMMSMSAMXMAAMXMSMMMAMXMMAAXSMXSASMXSAMXSSXSMAAXAXMXXAMMSMMMMSMAXAAMAMMXMAXAMSMSMAAAMAMSAMAAAMMSSXSASAMAMMAASXMSMSMAXMAAMXMAMMXMMASMMMAXAMXX
XXXSXMXXAMMSMMAMAAAMXMXMASMMXAXMMMMXMXSSXMAAXXSMSSSMSASXMASXAAMAMMXXAMMXXAMXMXAAXMXMMAMSAMSSMSXXMMMXMAMASMMMMASXAXMXMMMMMASMSXMMSAMASXSMSSSS
MMMSAMXSMMMAASMSSSMSAXXSAAXXMSMMSAMAMXMXAXMASXXAXAXAMXAAMSXMXMSMMXMXSSMSMXMASMSMSSMXSAMMAMXAASAMXAAAMMMASAMASXMMMMSAAAXASXSAAXMAMAXMMAMAXAAA
XAXMAMMSAAXSXMAAAMASMMMASAMXMXAAXASASAXMXMXAMMMXMASXMSSSMMXSMMAXXAASXAAAASAXMAXAXAAAMXSSSMMMMMASMSSMXSAMMASASMMMAAMASMSXSASMMSAASAMSMMMSMMMM
SSSSXMASMMXMAMMMSMAMAXXAXXXAMMMMSASASMSMSMMXSAMAMXMAMMMMAXAAMSAMSXSAMMMMXSAMXSMSMMMMSAMAMXMMASAMXMAMAXAMSXMMSASMMMSAMMSAMXMAAXMXMAXXAAAAMSXM
SAAXSMXXMMASXMAMAMASMMMXMAMMSXXAAMMAMXAAAXSMSASMSSSSMAAMXMXMAMAXXMMMMSAXMSAMAXAAAXAAMMSAMAXSXSXSXSAMXSMMXAAMSAMMAAMASAXAMAMXMAXMSSSSSMSSXXAS
MMMMMMSXMMASAMASASMSXAXMMSMSAMMSSXMAMSMSMXSAMXMAAAAMSMMSXMSXMSSMSMAAXMAXMMAMXMMMSSMXSASASAXSXMAMAMMMMXMASAMXMAMMSMMMMMMMSXSSMMXXAAMAAAAXMSMM
SXAAAAXMSMMMXSASASASMXSXXAMXASAAMMSSXSXAXXMXMAMMMMMMAMSAMXAAMAMXXMMMMXMASXXMAMMSMMMMMMMMMMXMASXMSMMSAMMAAAXMSMMMAXAAAAXXAMXAAMAMXSMSMMMSAAAA
ASXSMXSAXXAAXMXMAMAMMMMXMASMMMMXMAAMXMASMXMAMXSAXXXXAXXMAXMMMASMXXMASXSXSAMSSSMAAMSMSASXMASMXMASAAXAMSMSSSMAXMASMSSSSXSAMSSSMMAAAMMXXMASXSMM
XSXMAAMXMSMSSMXMAMSMMAAXSAMXXSXSMMSSMMMMSMXAMXAMAMXSSSSSSMSASXMASXAAAAMAMXMAXAMSSMAAXAASXMXXMASXMSMMXMAAAAMSMSMXXMMAAAMXXXXAMSMSSSMSAMXMXMAM
XSAMMMMAMAMMXMAMAXMASMXXAXXAMXAMXAAMMSAMASMSXSASMSAAXAAAAAAAMXMASXSAMXMAMXMMSSMMAXMSMMMXMASXMMXXMAMXSMMMSMMAAAAXSAMMMXMASMSMMAAXAAXXMXMMAMAM
SMAMMAMASAXMAMSSSSSXMMMSMSMSSMMMMMMSAMASAMXAAMAMMMMMXMMSMMMAMAMMMAXMSASXMXAAAXASAMXAXAASXMXASASASMSASMAMAMXMMMSASMXXMAXAAAAAXMSMSMMXMAAMXSAM
MSMMSAMXSASXSMAAMXMXMXXAXMMAAAXSAMXMXMAMMXMXMMMMSMSXXXXXMXMASASAMSMASMSAMSMMXSXMMXSMSXXMAXXXMASAMAMXSSXXASXSAAAMXAXAMMMSSMSSMAMAAMAAXXXAASAM
XMMASMSMMAMAAXMXMASMMASMSSMSSMMSASAMSSSMAAXMMAMXMASMMXMASMSASAMXMAMXMAMXXMASASXAAXAXXMASMMMSMXMMMAMXMAXSAMASMSMXMMMMSMAMAXAAMAMMMSSMSMXMXMSS
MSMASXAXMXMSMMXASMMAAAXXAAAAAAAXMSAMXAAMSXSAXASAMXMAMXMXMMMASASXSMSSMAMAASAMAXSXMXSMMSMAMAAAMXAMMAMMMAMMAMXMMXXXAXAXAMASXMSSMSSXMAMMAMSMSMAM
AAMASXSSXSMMXAXMXMXAMSMMMXMMXMMSXSMMMSMMAMAXSMMASXSSMMSMMAMXMASAAXAXSAXXXAMMSMSMSMMMAAXASMSXSSMMSMSMMSSSMSMSXMMSSSMXMXASMAMAMAMMMASMAMSAAMAM
SMSASAMSAAXAXSXSASMSAMASXMSSXAXMXMAMAXAMXSAMMXMAMXAAMAAAXMASMAMMSMSMSMXMXAXAMAXMAAMMSSSXSXMXAAXXAAAMSMAXAAAMMMAAMAMMMASXMASAMASAMXMMXSMSMSXS
XXAXMASMXMMASMAMASMMASAMAMAASMMSAXMMASAMMMASXSASXMMMMSSSMXXXMXMSXAXAMMASXMMSMAXSMSMAAAMASAMMSMMSMSMMAMSMSMMMAMXMXAMMMXMASASXMMMMSMXSMMAMXXAA
XAMXSSMMMXMXAMAMXMASXMASXMSXMSSSXSSMMMAMASXMASMXAMXXXXMMAMXMXSMMMSMSMSASAAAXMXMXAXMXSXMAMSMAXSMXAAMSSSMAMASMXSXMMASAMASAMXSASXAAXAMXAMAMAMAM
XMXMXMAASXMSAXMSXMAMXMXMXAXXAXMXAAXAXSSMMMSMXMXSAMXMSAMXSMAMASAAAMXXAMASAMXMSSXMAMMAXAMXXXMSSMSMMMXMXAMAMXMMAMAASASASMSAMXMAAMMMXXMSSMASAMAA
MMAMXSXMSAXSAMSAXMXSAXASMXMMAMMMSMSSMMXAXAXMASASMMAAMSMAMMXSASMMMSSMAMMMXSXSASXMASXMMXMSAMXXXAAXAMXMSXMMSSMMAMXMMASXMXXMMSMMMSSXSAMAXMASASXS
ASASASAMMMMMMMMAMSASMSMSAAAAASAAAXAAAMXMMXMAAMASXSXXSAMXSSMMASXMXAAMMSMSAMXMASXXAMAMXSAMAMMMMSMSMSAMXXMASAASMSMXMMMMMSMMAXASXXAASXMXSMXSAMXX
XSASASXMAAAAAXMMMMASXAMMXXSSMXMSXMXSMMASASMMSSMMXSAMSAMAMXASAMXSMXXMAAMMASMMMMAXXSASAMXSAMAAAAAAASASXXMMMMMAAXAMMAAXAAAMASAMSMMMMMMASAAMXSXS
XMMMMMMSMSSSSMXMAMXMMSSMSXMAXMMXASMMAXXMASXAAAAMXMAMSXMAXMXMAXAXSMAMSSMXAMXMMMSMMAMMAMASXXXXSXSMMMASMMASASXSMSSSXSMMSSXMAMAMXXAAAAMMSMXMASAS
MSMSAAXMXXAAXAMMAXSMSMAMSASAMMASXMASAMXMSMMMSSMMAMMMMXSMSSSSSMSAMXAMAMMMSMSSXMASAAMSXMXMMSSMMMMMXMMMASASMSAMXAAMAMXMAXAMXXXSMXSXSXSAMAMSAMAM
AAASXSXSSMMMMSSXSSMMAMXMSAMMSMAXSAXSMSAXAXAMXXMMSXSASXMSAAAAXAXAASASASXMMAAMAMAMSAXXXMAAAAXAAXSAAMAXXMASMMMMMMSMAMAAAMXMAMXMXMMAXAMASAMMMMSM
MMMMAXAXSXAAAXXAMAXAASMAMAMAAMMSMSMMXSAMMXSMMASAMXSASASMSMMMMSMSXSASMSAAMMMMMSAMXMASASXMMSSSMMMSSSXMSMXMASAXXMXMASMMSMAXASASAMXAMASAMMSMSAXS
XXASAMXMMSSSSSMSMAASMSMASAMMXSXAAAXXAMXMSAXASXMAMAMMMMMMXSXXXMAAAXXXXSMMXMXXXMASXXAXMXXMAMAMAMAAMAMASAMXMMMASXSMAAAAXMAXASASAMMASXMMXSAMMASX
MMXXASXSMAXMAAAAMXMXAXXAMASMMMMMSMXMXSSMXASAMXXAMAMXAAAMXMMMMMXMXMXMAXXMXSMMMSXMXMMSASXSSXMASMMMSAXXXXXXXMXMAAAAMMMSMSMXMMXMAMSMMMSAXSAXMMMX
XMMSAMAMMMSSSMMMSMXMASMSSSMXAAAXAMXMAMAMMMMAMMSMSXSSMMMXAMMAAXAMAMMMXXXSAMAAAMAAXAAMAMAAXXXXXAXMMMXXMMSXMMAMMSMMMXMAAAMMMAAMAMAAAAMMAMAMSAMM
AAAMMMAMMMAAAAXAAMXMMMAMXMASMSMMAMXMASAMAXMMXMAMAMXAAAMSMXASMSMSASXSMMMMMSSMMSSMXSAMMMMMMSMMSXMAAXSAAASASMXSAMXXMXMMSMSASXMSASMSMSSXAMSMSASX
SMXSASMSMMMSMMMSSSXXAMXMAMAMMAXSMSMSAMXSMXXMASMSXSXMSMXASXAMXAASXSAMXAAAXMASAXAMAXAXSXMSAXAAMAMSMAASMMSAMXAMAXMASXMAMMSMSAMXASAAXMAMXSAASAMA
XXAMAMAAXAAMXAAAAMMSXSMSXSAXXAXSAAAMMMMMAMSSMSASAXXMAXXAMXMSMMMMMMMMSXSMMSAMXSAMAMMMSAAMSSMMSAMAMXMMXAMAMMXMXAXSXMMASXMXMAAMAMMMMXMMMMMMMSMM
SMSMSMSMSMSSMMXXSAMSASASAMXSMSSMSSSMSASMAMAAXMAMMMXMASMMMXMAMMAMAAAXMAMAMXSAMXXMASAASMMMAMMAMXSXMMXMSMSMMASXSMSMXAXASMMMASAXMASMXXAAAXMAAXMX
XAXAMAXAAAAXXAXSMXSMAMSMAMAXXMAAAMAASXSSMSSMMMMMMXXSAMXAMAMAMSASMXSAMAMAMMMMXMSAMAMMMAAMXXAXSAXMXAAAXMAXSAXMMSAMSSMASAMAAXSXMASAASMMMSSMXSAM
MSMAMSMSMSSSMMMXASXMXMXXXMASMSMMMSMMMMXAMAXXAXAAMMXMXMXASAXAMSASAAMMMXSXMSAXSAMXXMMSSSMSMSXMAXMSASMMSSMXMSSSXXMMAAMAMXMMSXMMSAMMMMSAMXXMSAMX
SMSXMAMXXAAMASAMMSAMXAMXXMSAMXXMASMAAMMMMMSSMMSASXMMASMXSMMSAMXMMMMAMMMMAMXMAASAMXXAXMAXAAXSAMSXMAAAAAMSAMXMAMXMSSMASAMXMASAMASXMASMMXAXMASA
XAAMSMSSMSMSAMXSASAMAAXMSMMMSMMMAXMSXSAXAXXASAXXXMASASMMMMAMASASXSMMMAAASXMMSMMXAAMMSMMMSMMMAMAMXSMMSSMMXSAMAMXMAAMXSMSAXAMAMAMAMASXMXMASXMM
MXMAAXMAAAMMXSSMMSAMSMXMASAAAASMSSXMASMSMMSAMXSSMSXMAMMAMMXXMMMMAMASMSSXMASAMAXXMSSXAASXXASMMMASMMAAAAAAASASASXMXSMXXAMAMSSMMSSSMAXAXAMXMSSS
ASMSSSMMSMXMAMXAXMMMAAMSASMMSSMAAAMSASXSAAAAXAXAXAMMSMSSSMSMXAXMAMAMAMXASXMASXMASAXXSSMASAMASXSMASMMSSMMMSXSXSXSAXAMMMSSXMAXAXAMMSSSMSXXMAMX
SXAAXAXMMXMASASMMMSSMSMMASAAMAMMMSMXASASMMXXMXMASMSMMAMAXAAAMMSXSSMMXMXXMASAMAXMXXSAMAMXMXMMMXASAMAAXXAXXMXSAMAMAMSAAXAXMXMMXMSMMAAAAXAXMXSM
XMMMSAMXMMSAMAXMASMSXAXMMMXMSAMMXAXXXMXMASMXMXSAXMAXMAMAMMMSAASMMAXMSSXMMAMMSMAMAAMMXAMXMAMAMSMMXSMSSSSMASAMAMMMXMASMMSXSASAMMAMMMSMSMMMSMAM
MAAAAAAXXAAAMMMSMSAMSAMSAMXXSAMXSMMXSAXMAAXSAMMMSSSSSMMXSXAXMMMMSAMXAAXMMSXMAXAMAMSSSSSSSMXAMMSMAXAXAAMSMMASAMXMMAMAMXMASASAXSASXXAXXAAAXMAM
SSMSSMMMMXMAMXAMMMMMMMASAXXAXMMXXAAASXSMSMSASXAXXAXXAXMASMSMXMAAMXMMMSSXAMASMSMSMMAAAAAAAASMSMAMMMMMMMMAXXAMXSAMSMMMSAMAMXSMMSXSXXMXSMMXSMSS
MXMXMMASXSXAMAXMSMAXXSAMMSASAMSSSMMMSAMXMXAMXSMMMMMSAMMXXAXXXMASMMMAXAMMASAMAAAAMMMMMMMMMMXAAXXSAXMAXASXXSAMASMXAAAAXXSAMXXMASXMMMMMSXXAMAXA
MAMXMSMSAMXSMMXMAAAXXMASAMXXAXAAMXMAMAMASMMXXAMXAAAMXASMMSMSMMAAASXAMASAMMXMXXMASXSAMXXXSMMSMMMSASMXMAXAASXMAMMXSSMSMASAXXAMASAXAAAAXAMSSSMA
SMSAAAXXXMAMAMASMSXXAMXMMSSSMMMSMAMASAMASMXMSMMSSMSXSSMAXAAASMXSAMMMSAXMAMXMASMXXAXAXXSXAMMXMXXSAMAMMSMMXMSMSXSAAXAXMASMMSXMXSMMSMXXMXMAAASX
AASMSMSXAMXSASAMXAASAMAMXAAAXAAAXASASAMASXAAAAMXMAAMSAMSSMSASMAMAXSAMXSMXSAMMXMMMMSMMMMSMSMAMSMMAMAXAXAXSAMXMAMMSMMMMASAAXAXAXXAMMSMXAMMSMAX
MMMXAAXMAMXSAMXSMXMSASASXMSMMSSSSXSASAMXSXMSSSMAMMMMSAMMSXMASMXSXMSAMXMAASASAAAAAXAXAXAAXAMMSAASAMXMASAMXSMAMAMAAAASMASMMSXMMSMMSAAASXSAAXMS
XSXSMSMXSMXMAMSAMMMSMSXSXXMAXAMMMASAMXMASMMAMXXSMXSAMXSMSXMAMMMAMXMXXMASMSAMMSSSMSAMXSSSSXSMSAMSSSXMAMXAMXSXSXMSSSMSAMXMXMASXXMSMMSMMMMXSSXM`;
